UPDATE pago SET estado = 'PENDIENTE' WHERE estado IS NULL;
ALTER TABLE pago MODIFY COLUMN estado VARCHAR(25) NOT NULL DEFAULT 'PENDIENTE';

UPDATE pago SET medio_pago = 'TRANSFERENCIA' WHERE medio_pago IS NULL OR medio_pago NOT IN ('DEBITO', 'CREDITO', 'TRANSFERENCIA');
ALTER TABLE pago MODIFY COLUMN medio_pago VARCHAR(50) NOT NULL;
